# Generated by Django 6.0.7 on 2026-08-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={
                "ordering": ("last_name", "first_name"),
                "verbose_name": "Crew",
                "verbose_name_plural": "Crews",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ("flight", "row", "seat"),
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
