# Generated by Django 6.0.7 on 2026-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_airplane_airplane_type_alter_airport_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="airplanes/"),
        ),
    ]
