# Generated by Django 6.0.7 on 2026-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_airplane_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="flag",
            field=models.ImageField(blank=True, null=True, upload_to="flags/"),
        ),
    ]
