# Generated by Django 6.0.7 on 2026-08-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_country_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cities/"),
        ),
    ]
