# Generated by Django 6.0.7 on 2026-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_city_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="airports/"),
        ),
    ]
