# Generated by Django 6.0.7 on 2026-08-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0007_airport_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplane",
            old_name="image",
            new_name="airplane_image",
        ),
        migrations.RenameField(
            model_name="airport",
            old_name="image",
            new_name="airport_image",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="image",
            new_name="city_image",
        ),
        migrations.RenameField(
            model_name="country",
            old_name="flag",
            new_name="country_flag",
        ),
    ]
